# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Jul  7 08:57:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1107, 635)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Movies = QtGui.QWidget()
        self.Movies.setObjectName(_fromUtf8("Movies"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Movies)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_6 = QtGui.QLabel(self.Movies)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 6, 7, 1, 1)
        self.year = QtGui.QLineEdit(self.Movies)
        self.year.setObjectName(_fromUtf8("year"))
        self.gridLayout_3.addWidget(self.year, 7, 6, 1, 1)
        self.label_2 = QtGui.QLabel(self.Movies)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.Movies)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 5, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.searchText = QtGui.QLineEdit(self.Movies)
        self.searchText.setObjectName(_fromUtf8("searchText"))
        self.horizontalLayout_2.addWidget(self.searchText)
        self.searchCategory = QtGui.QComboBox(self.Movies)
        self.searchCategory.setObjectName(_fromUtf8("searchCategory"))
        self.horizontalLayout_2.addWidget(self.searchCategory)
        self.search = QtGui.QPushButton(self.Movies)
        self.search.setMaximumSize(QtCore.QSize(40, 16777215))
        self.search.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/1404682038_27877.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search.setIcon(icon)
        self.search.setObjectName(_fromUtf8("search"))
        self.horizontalLayout_2.addWidget(self.search)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 523, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 10, 1)
        self.label_7 = QtGui.QLabel(self.Movies)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 7, 5, 1, 1)
        self.director = QtGui.QLineEdit(self.Movies)
        self.director.setObjectName(_fromUtf8("director"))
        self.gridLayout_3.addWidget(self.director, 3, 6, 1, 3)
        self.poster = QtGui.QLabel(self.Movies)
        self.poster.setMinimumSize(QtCore.QSize(320, 476))
        self.poster.setMaximumSize(QtCore.QSize(320, 476))
        self.poster.setFrameShape(QtGui.QFrame.Box)
        self.poster.setFrameShadow(QtGui.QFrame.Sunken)
        self.poster.setAlignment(QtCore.Qt.AlignCenter)
        self.poster.setObjectName(_fromUtf8("poster"))
        self.gridLayout_3.addWidget(self.poster, 2, 4, 9, 1)
        self.label_8 = QtGui.QLabel(self.Movies)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 7, 7, 1, 1)
        self.label_5 = QtGui.QLabel(self.Movies)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 6, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.Movies)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 10, 5, 1, 1)
        self.plot = QtGui.QTextEdit(self.Movies)
        self.plot.setObjectName(_fromUtf8("plot"))
        self.gridLayout_3.addWidget(self.plot, 10, 6, 1, 3)
        self.addFolder = QtGui.QPushButton(self.Movies)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/1404683777_27849.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFolder.setIcon(icon1)
        self.addFolder.setObjectName(_fromUtf8("addFolder"))
        self.gridLayout_3.addWidget(self.addFolder, 11, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.save = QtGui.QPushButton(self.Movies)
        self.save.setMaximumSize(QtCore.QSize(60, 16777215))
        self.save.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/1404682264_27876.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon2)
        self.save.setIconSize(QtCore.QSize(40, 32))
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout.addWidget(self.save)
        self.play = QtGui.QPushButton(self.Movies)
        self.play.setMaximumSize(QtCore.QSize(60, 16777215))
        self.play.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/1404682048_27865.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon3)
        self.play.setIconSize(QtCore.QSize(40, 32))
        self.play.setObjectName(_fromUtf8("play"))
        self.horizontalLayout.addWidget(self.play)
        self.info = QtGui.QPushButton(self.Movies)
        self.info.setMaximumSize(QtCore.QSize(60, 16777215))
        self.info.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/1404682274_27854.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info.setIcon(icon4)
        self.info.setIconSize(QtCore.QSize(40, 32))
        self.info.setObjectName(_fromUtf8("info"))
        self.horizontalLayout.addWidget(self.info)
        self.gridLayout_3.addLayout(self.horizontalLayout, 11, 6, 1, 1)
        self.label_12 = QtGui.QLabel(self.Movies)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 9, 5, 1, 1)
        self.addMovie = QtGui.QPushButton(self.Movies)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/1404682250_27831.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addMovie.setIcon(icon5)
        self.addMovie.setObjectName(_fromUtf8("addMovie"))
        self.gridLayout_3.addWidget(self.addMovie, 11, 0, 1, 1)
        self.remove = QtGui.QPushButton(self.Movies)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/1404682064_27842.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove.setIcon(icon6)
        self.remove.setObjectName(_fromUtf8("remove"))
        self.gridLayout_3.addWidget(self.remove, 11, 2, 1, 1)
        self.genre = QtGui.QLineEdit(self.Movies)
        self.genre.setObjectName(_fromUtf8("genre"))
        self.gridLayout_3.addWidget(self.genre, 7, 8, 1, 1)
        self.label_4 = QtGui.QLabel(self.Movies)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 4, 5, 1, 1)
        self.rated = QtGui.QLineEdit(self.Movies)
        self.rated.setObjectName(_fromUtf8("rated"))
        self.gridLayout_3.addWidget(self.rated, 6, 8, 1, 1)
        self.title = QtGui.QLineEdit(self.Movies)
        self.title.setObjectName(_fromUtf8("title"))
        self.gridLayout_3.addWidget(self.title, 2, 6, 1, 3)
        self.runtime = QtGui.QLineEdit(self.Movies)
        self.runtime.setObjectName(_fromUtf8("runtime"))
        self.gridLayout_3.addWidget(self.runtime, 6, 6, 1, 1)
        self.label_9 = QtGui.QLabel(self.Movies)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 8, 5, 1, 1)
        self.imdb = QtGui.QLineEdit(self.Movies)
        self.imdb.setObjectName(_fromUtf8("imdb"))
        self.gridLayout_3.addWidget(self.imdb, 9, 6, 1, 1)
        self.label_10 = QtGui.QLabel(self.Movies)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 9, 7, 1, 1)
        self.tomato = QtGui.QLineEdit(self.Movies)
        self.tomato.setObjectName(_fromUtf8("tomato"))
        self.gridLayout_3.addWidget(self.tomato, 9, 8, 1, 1)
        self.awards = QtGui.QLineEdit(self.Movies)
        self.awards.setObjectName(_fromUtf8("awards"))
        self.gridLayout_3.addWidget(self.awards, 8, 6, 1, 3)
        self.cast = QtGui.QTextEdit(self.Movies)
        self.cast.setMaximumSize(QtCore.QSize(16777215, 80))
        self.cast.setObjectName(_fromUtf8("cast"))
        self.gridLayout_3.addWidget(self.cast, 4, 6, 1, 3)
        self.writers = QtGui.QTextEdit(self.Movies)
        self.writers.setMaximumSize(QtCore.QSize(16777215, 80))
        self.writers.setObjectName(_fromUtf8("writers"))
        self.gridLayout_3.addWidget(self.writers, 5, 6, 1, 3)
        self.label_13 = QtGui.QLabel(self.Movies)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 5, 5, 1, 1)
        self.listWidget = QtGui.QListWidget(self.Movies)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_3.addWidget(self.listWidget, 3, 0, 8, 3)
        self.tabWidget.addTab(self.Movies, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Personal Movie Manager", None))
        self.label_6.setText(_translate("MainWindow", "Rated", None))
        self.label_2.setText(_translate("MainWindow", "Title", None))
        self.label_3.setText(_translate("MainWindow", "Director", None))
        self.label_7.setText(_translate("MainWindow", "Year", None))
        self.poster.setText(_translate("MainWindow", "Poster Not Available", None))
        self.label_8.setText(_translate("MainWindow", "Genre", None))
        self.label_5.setText(_translate("MainWindow", "Run Time", None))
        self.label_11.setText(_translate("MainWindow", "Plot", None))
        self.addFolder.setText(_translate("MainWindow", "Add Folder", None))
        self.label_12.setText(_translate("MainWindow", "IMDB", None))
        self.addMovie.setText(_translate("MainWindow", "Add Movie", None))
        self.remove.setText(_translate("MainWindow", "Delete", None))
        self.label_4.setText(_translate("MainWindow", "Cast", None))
        self.label_9.setText(_translate("MainWindow", "Awards", None))
        self.label_10.setText(_translate("MainWindow", "Tomato", None))
        self.label_13.setText(_translate("MainWindow", "Writers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Movies), _translate("MainWindow", "Movies", None))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

